# Generated by Django 6.0.2 on 2026-02-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_skill_profile_resume_profile_short_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture.', null=True, upload_to='profiles/'),
        ),
    ]
