# Generated by Django 6.0.2 on 2026-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('LANGUAGE', 'Language'), ('TOOL', 'Tool/Platform'), ('SOFT_SKILL', 'Soft Skill'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
