# Generated by Django 6.0.2 on 2026-02-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('credential_url', models.URLField(blank=True, help_text='Link to the credential.', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts_app.profile')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
    ]
